# ICC2_smokeのコンパレータ設定
execute_command: python ICC2_smoke.py
old_artifact_pattern: ICC2_smoke_{old_version}.txt
new_artifact_pattern: ICC2_smoke_{new_version}.txt
input_files:
  - sample1.txt
  - sample2.txt
parameters:
  - -o
  - "{output_file}"

# 比較メソッド設定
comparison_methods:
  # 基本的な比較方法
  format_check: true
  line_count: true
  content_diff: true
  
  # キーワード検証
  keyword_check:
    - "タイミング違反"
    - "処理時間"
    - "メモリ使用量"
  
  # カスタムパターン検証
  custom_patterns:
    - name: "タイミング違反パターン"
      pattern: "タイミング違反: (\\d+)件"
    - name: "処理時間パターン"
      pattern: "処理時間: (\\d+\\.\\d+)秒"
    - name: "メモリ使用量パターン"
      pattern: "メモリ使用量: (\\d+)MB"
